# Generated by Django 3.2.5 on 2021-09-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cita_me_gusta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
